rdfs = "http://www.w3.org/2000/01/rdf-schema#"
rdf  = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
shl  = "http://www.library.sh.cn/ontology/"
bf   = "http://id.loc.gov/ontologies/bibframe/"
dc   = "http://purl.org/dc/elements/1.1/"
fzwc = "http://www.fzwc.online/ontology/"